version: '3.5'

services:
  financeiro:
    build:
      context: '.'
    container_name: financeiro
    ports:
      - 80:80
    volumes:
      - .:/var/www/html/
    depends_on:
      - "financeiro-db"
      - "financeiro-mail"
    networks:
      - app

  financeiro-db:
    image: mysql:8
    tty: true
    container_name: financeiro-db
    ports:
      - 3308:3306
    environment:
      - MYSQL_ROOT_PASSWORD=123
      - DB_CONNECTION=mysql
      - DB_HOST=financeiro-db
      - DB_PORT=3306
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - SERVICE_TAGS=dev
      - SERVICE_NAME=mysql
    networks:
      - app

  financeiro-mail:
    image: mailhog/mailhog:latest
    container_name: financeiro-mail
    ports:
      - "8125:8025"
      - "2525:1025"
    environment:
      - MT_USER=financeiro
      - MT_PASSWD=financeiro
      - MT_MAILBOX_LIMIT=512000001
      - MT_MESSAGE_LIMIT=102400001'
    networks:
      - app
    
  financeiro-redis:
    image: redis:latest
    container_name: financeiro-redis
    ports:
      - 6379:6379
    networks:
      - app
networks:
  app:
    driver: bridge
